name: Pull Request Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  pr-pipeline:
    uses: PruebaActions/WorkFlows-Templates/.github/workflows/pr-dotnet-codeql.yaml@main
    with:
      image_name: myapp-pr
      container_name: myapp-pr-container
      dockerfile: ./Dockerfile
      port: '8080'
      codeql_languages: 'csharp'
